export const projects = [
  {
    id: 1,
    image: "",
    thumbnail: "IMG-20251014-WA0118.jpg",
    folder: "lavington",
    title: "Installation of extractor fans and motion sensors in Lavington",
    date: "December 2024",
    images: [],
  },
  {
    id: 2,
    image: "",
    thumbnail: "IMG-20251014-WA0115.jpg",
    folder: "fairview-hotel",
    title: "Installation of coldroom door latches at Fairview Hotel",
    date: "November 2023",
    images: [],
  },
  {
    id: 3,
    image: "",
    thumbnail: "IMG-20251014-WA0112.jpg",
    folder: "ocp-kenya",
    title: "Installation of new extractor fan OCP Kenya in Westlands",
    date: "",
    images: [],
  },
  {
    id: 4,
    image: "",
    thumbnail: "IMG-20251014-WA0110.jpg",
    folder: "msingi-ea",
    title: "Installation of new air conditioning units Msingi East Africa Westlands",
    date: "",
    images: [],
  },
  {
    id: 5,
    image: "",
    thumbnail: "IMG-20251014-WA0094.jpg",
    folder: "genafrica",
    title: "Service and maintenance of air conditioning equipments at Genafrica Westlands",
    date: "",
    images: [],
  },
  {
    id: 6,
    image: "",
    thumbnail: "IMG-20251014-WA0099.jpg",
    folder: "standard-street",
    title: "Standard Street",
    date: "15 April 2025",
    images: [],
  },
];
