export const projects = [
  {
    id: 1,
    thumbnail: "IMG-20251014-WA0118.jpg",
    folder: "lavington",
    title: "Installation of extractor fans and motion sensors in Lavington",
    date: "December 2024",
  },
  {
    id: 2,
    thumbnail: "IMG-20251014-WA0115.jpg",
    folder: "fairview-hotel",
    title: "Installation of coldroom door latches at Fairview Hotel",
    date: "November 2023",
  },
  {
    id: 3,
    thumbnail: "IMG-20251014-WA0112.jpg",
    folder: "ocp-kenya",
    title: "Installation of new extractor fan OCP Kenya in Westlands",
    date: "",
  },
  {
    id: 4,
    thumbnail: "IMG-20251014-WA0110.jpg",
    folder: "msingi-ea",
    title: "Installation of new air conditioning units Msingi East Africa Westlands",
    date: "",
  },
  {
    id: 5,
    thumbnail: "IMG-20251014-WA0094.jpg",
    folder: "genafrica",
    title: "Service and maintenance of air conditioning equipments at Genafrica Westlands",
    date: "",
  },
  {
    id: 6,
    thumbnail: "IMG-20251014-WA0020.jpg",
    folder: "riverside-drive",
    title: "Installation of new outdoor unit at 14th Riverside Drive Westlands",
    date: "",
  },
  {
    id: 7,
    thumbnail: "IMG-20251014-WA0079.jpg",
    folder: "gsma",
    title: "Installation of new LG multy v 5 system at gsma",
    date: "January 2025",
  },
  {
    id: 8,
    thumbnail: "IMG-20251014-WA0036.jpg",
    folder: "brookehouse-runda",
    title: "Service and repair of air handling unit at Brookehouse Runda",
    date: "September 2022",
  },
  {
    id: 9,
    thumbnail: "IMG-20251014-WA0036.jpg",
    folder: "brookehouse-runda",
    title: "Installation of new printed circuit board and fan motor at Alpha business park",
    date: "August 2022",
  },
  /* {
    id: 6,
    image: "",
    thumbnail: "IMG-20251014-WA0099.jpg",
    folder: "standard-street",
    title: "Standard Street",
    date: "15 April 2025",
    images: [],
  }, */
];
